# Plasma flow around a spherical object (2D)
[file]
output = data_plasma_sphere/

[time]
NUM_TS = 30000
DT_coeff = 0.01

[diagnostics]
write_interval = 50
write_interval_phase = 500
write_diagnostics = 100
write_flag = 1
save_fig = 1
sub_cycle_interval = 20
precision = 4
diagtype = full

[PlotFlags]
phase_space     = 0
config_space    = 1
electric_field  = 0
potential_field = 0
density_contour = 0
ke_components   = 0
total_energy    = 0
species_index   = 0

[domain]
Nx       = 50
Ny       = 32
x0       = 0
y0       = 0

[Grids]
grid_count = 1

grid_0.type = circular
grid_0.x_center = 16
grid_0.y_center = 16
grid_0.electrode_number = 1
grid_0.grid_radius = 4
grid_0.electrod_radius = 5
grid_0.electrode_voltage = 1000

[Emitters]
count = 1

# Inject plasma from the left boundary to create a flow past the object
emitter_0.x0 = 0
emitter_0.y0 = 10
emitter_0.x1 = 0
emitter_0.y1 = 20
emitter_0.temp = 0.0
emitter_0.numparticle = 1
emitter_0.vdx = 0.0
emitter_0.vdy = 0.0
emitter_0.species_idx1 = 0
emitter_0.species_idx2 = 1

[normalization]
# 1 = electron scale, 2 = ion scale, 3 = subcycling, 4 = mixed, 5 = custom
norm_scheme = 1
vel_norm_scheme = 1
lenght_scale = 0.001
time_scale = omegape
energy_scale = 1

[solver]
solvertype = gs
tolerance = 1e-3
max_iteration = 4000

[simulation]
shapefunction = NGP
#push_parallal = false
#deposit_parallal = false
density = 1E13
bc = open
ionfixed = 0

[ExternalField]
B = 0.5
theta = 90
azimuth = 0

[collision]
# true / false
elastic = false
excitation = false
ionization = false
pion_elastic = false
nion_elastic = false
e_detach_collision = false
GAS_DENSITY = 0
collgroup = 01
GAS_TYPE = AR

[Species]
count = 2

species_0.name = electron
species_0.mass = 9.10938215E-31
species_0.num = 100
species_0.temp = 1.0
species_0.charge_sign = -1
species_0.normden = 1.0
species_0.vsx = 0.0
species_0.vsy = 0.0
species_0.loadtype_posx = random
species_0.loadtype_posy = random
species_0.loadtype_velx = uniform
species_0.loadtype_vely = uniform

species_1.name = ion
species_1.mass = 1.6726219e-27
species_1.num = 100
species_1.temp = 0.1
species_1.charge_sign = 1
species_1.normden = 0.0
species_1.vsx = 0.0
species_1.vsy = 0.0
species_1.loadtype_posx = random
species_1.loadtype_posy = random
species_1.loadtype_velx = uniform
species_1.loadtype_vely = uniform
