# 2D template synced to 1D layout
[file]
output = data/
		
[time]
NUM_TS = 50000
DT_coeff = 0.001

[diagnostics]
write_interval = 50
write_interval_phase = 500
write_diagnostics = 50
write_flag = 1          
save_fig   = 1
sub_cycle_interval = 20
precision = 4
diagtype  = full

[PlotFlags]
phase_space     = 1      #1 = plot phase space (x vs vx), 0 = off
config_space    = 1      #1 = plot config space (x vs y), 0 = off
electric_field  = 0      #
potential_field = 1
density_contour = 0
ke_components   = 1      #1 = plot kinetic energy components, 0 = off
total_energy    = 1      #1 = plot total energy plot, 0 = off
species_index   = 0

[domain]
Nx       = 256
Ny       = 256
x0       = 0
y0       = 0

[Grids]
grid_count = 0

[Emitters]
count = 0

[normalization]
# set 1 for electron scale, 2 for  ion scale, 3 for  subcycling and 4 for  lenght ion and time electron.
# set 1 for electron thermal velocity, 2 for  ion thermal velocity and  3 for  ion acoustic velocity.
norm_scheme = 1
vel_norm_scheme = 1
lenght_scale = 0.001
time_scale = omegape
energy_scale = 1
          
[solver]
solvertype = spectral           
tolerance = 1e-2
max_iteration = 100

[simulation]
shapefunction = CIC
push_parallal  = false             
deposit_parallal = false
density = 1E13			   
bc = pbc
ionfixed = 0

[ExternalField]
B = 0.000
theta = 0
azimuth = 0

[collision]
# true /false
elastic    = false
excitation = false
ionization = false
GAS_DENSITY = 1e20           #Neutral gas density(only argon in implemented here)
collgroup = 01,21          

pion_elastic = false
nion_elastic = false
e_detach_collision = false
GAS_TYPE = AR

[species]
#name of species, mass,number of particle, temparature, charge sign, ratio of species density to electron density, 
#velocityx,velcity y, load
electron,9.10938215E-31,40000,1.00,-1,1,0,0,uniform
ion,1.6726219e-27,40000,0.026,1,0,0,0,uniform
negion,1.6726219e-27,40000,0.026,-1,10,0,0,uniform
beam,9.10938215E-31,40000,1,-1,1,20,0,uniform

